### ISSUE TITLE
Les événements qui se recouvrent font 

### ISSUE THREAD

**Issue by lporcheron** [toulibre/cdl-site-teasing#8]
Quand des événements se recouvrent comme c'est le cas entre certaines conférences de Monaie Libre et les pauses déjeuner, l'affichage du programme sur le site est cassé comme le montre le screenshot ci-dessous :
![screen shot 2016-11-05 at 14 41 09](https://cloud.githubusercontent.com/assets/395602/20030479/3fec7fa8-a366-11e6-96bb-90842835ed1c.png)

Pour le moment, les pauses déjeuner ont été desactivées pour que l'affichage du programme ne soit pas cassé.

**Comment by slestang** [comment]
Est corrigé par le commit d04f9cfaab388da857960f751fffe86482469070
